name: Deploy Web
on:
  push:
    branches: [main]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3' 
          
      - run: flutter pub get
      - run: flutter build web
      
      - name: Deploy to Web Repo
        run: |
          git clone https://github.com/isina-nejj/cv-flutter-web.git web_repo
          cp -r build/web/* web_repo/
          cd web_repo
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-update: $(date +'%Y-%m-%d %H:%M:%S')"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/isina-nejj/cv-flutter-web.git 
          main