name: unipath
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.0
  sembast: ^3.5.0+1
  sembast_web: ^2.4.1
  path: ^1.9.1
  path_provider: ^2.1.1
  http: ^1.1.0
  flutter_time_picker_spinner: ^2.0.0
  shamsi_date: ^1.1.0
  table_calendar: ^3.1.3
  persian_datetime_picker: ^3.1.0
  flutter_localizations:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  marquee: ^2.3.0
  cloud_firestore: ^5.6.8
  # persian_localization: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo/logo.png
  # fonts:
  #   - family: Vazirmatn
  #     fonts:
  #       - asset: assets/fonts/Vazirmatn-Regular.ttf
  #       - asset: assets/fonts/Vazirmatn-Bold.ttf
  #         weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"
